src/aecds/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from utilisateur import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('page.urls')),
    path("glossaire/", include('glossaire.urls')),
    path('journal/', include('journal.urls')),
    path('inventaire/', include('inventaire.urls')),
]

url_users = [
    path('login/', user_views.LoginView.as_view(template_name="utilisateur/login.html"), name="login"),
    path('logout/', user_views.LogoutView.as_view(template_name="utilisateur/logout.html"), name="logout"),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name="utilisateur/password_reset.html"
            ),
        name="password_reset"),
    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name="utilisateur/password_reset_done.html"
            ),
        name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name="utilisateur/password_reset_confirm.html"
            ),
        name="password_reset_confirm"),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name="utilisateur/password_reset_complete.html"
            ),
        name="password_reset_complete"),
    path('profile/', user_views.profile, name="profile"),
    path('register/', user_views.register, name="register"),
]

urlpatterns += url_users

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/inventaire/urls.py
from django.urls import path
from . import views

app_name = 'inventaire'

urlpatterns = [
	path('', views.index, name='index'),
	path('annuaire/', views.annuaire, name='annuaire'),
	# RECHERCHE
	path('search/', views.SearchView.as_view(), name="recherche"),
	# ELEMENTS
	path('composants/', views.ComposantView.as_view(), name="composants"),
	# EXPORTATIONS
	path('sites/export/', views.export_sites, name="export-sites"),
	# SITE CRUD
	path('site/<slug:slug>/impression/', views.RapportPDFView.as_view(), name="site-print"),
	path('site/ajout/', views.SiteCreateView.as_view(), name="nouveau-site"),
	path('site/<slug:slug>/', views.SiteDetailView.as_view(), name="site-details"),
	path('sites/', views.SiteListView.as_view(), name="site-list"),
    path('site/<slug:slug>/modifications/', views.SiteUpdateView.as_view(), name="site-modif"),
    path('site/<slug:slug>/suppression/', views.SiteDeleteView.as_view(), name="site-delete"),
	# PARCELLE CRUD
	path('parcelle/ajout/', views.ParcelleCreateView.as_view(), name="nouvelle-parcelle"),
	path('parcelle/<slug:slug>/modifications/', views.ParcelleUpdateView.as_view(), name="parcelle-modif"),
	path('parcelle/<slug:slug>/suppressions/', views.ParcelleDeleteView.as_view(), name="parcelle-delete"),
	path('parcelles/', views.ParcelleListView.as_view(), name="parcelle-list"),
	path('parcelle/<slug:slug>/', views.ParcelleDetailView.as_view(), name="parcelle-details"),
	# BATIMENT CRUD
	path('batiments/', views.BatimentListView.as_view(), name="batiment-list"),
	path("batiment/ajout/", views.BatimentCreateView.as_view(), name="nouveau-batiment"),
	path("batiment/<slug:slug>/", views.BatimentDetailView.as_view(), name="batiment-details"),
	path("batiment/<slug:slug>/modifications/", views.BatimentUpdateView.as_view(), name="batiment-modif"),
	path("batiment/<slug:slug>/suppression/", views.BatimentDeleteView.as_view(), name="batiment-delete"),
	# NIVEAU CRUD
	path('niveaux/',views.NiveauListView.as_view(), name="niveaux-list"),
	path('niveau/ajout/', views.NiveauCreateView.as_view(), name="nouveau-niveau"),
	path('niveau/<int:pk>/',views.NiveauDetailView.as_view(), name="niveau-details"),
	path('niveau/<int:pk>/modifications/', views.NiveauUpdateView.as_view(), name="niveau-modif"),
	# MESURES SURFACE CRUD
	path('mesuredesurface/ajout/', views.MesureSurfaceCreateView.as_view(), name="nouvelle-mesuredesurface"),
	path("typedemesuredesurface/ajout/", views.TypeMesureSurfaceCreateView.as_view(), name="nouveau-typedemesuredesurface"),
	# MEMO CRUD
	path("memos/", views.MemoListView.as_view(), name="memo-list"),
	path("memo/ajout/", views.MemoCreateView.as_view(), name="nouveau-memo"),
	path("memo/<slug:slug>/", views.MemoDetailView.as_view(), name="memo-details"),
	path('memo/<slug:slug>/suppression/', views.MemoDeleteView.as_view(), name="memo-delete"),
	# RAPPORT
	path("rapports/", views.RapportListView.as_view(), name="rapport-list"),
	path('rapport/ajout/', views.RapportCreateView.as_view(), name="nouveau-rapport"),
	path('rapport/<int:pk>/modifications/', views.RapportUpdateView.as_view(), name="rapport-modif"),
	path("rapport/<int:pk>/suppression/", views.RapportDeleteView.as_view(), name="rapport-delete"),
	path("rapport/<int:pk>/", views.RapportDetailView.as_view(), name="rapport-details"),
	# AGENT CRUD
	path('agent/ajout/', views.AgentCreateView.as_view(), name="nouvel-agent"),
	path("agents/", views.AgentListView.as_view(), name="agent-list"),
	path('agent/<slug:slug>/', views.AgentDetailView.as_view(), name="agent-details"),
	path('agent/<slug:slug>/modifications/', views.AgentUpdateView.as_view(), name="agent-modif"),
	path("agent/<slug:slug>/suppression/", views.AgentDeleteView.as_view(), name="agent-delete"),
	# AGENTS DE SITE CRUD
	path('affectationagent/', views.AffectationAgentListView.as_view(), name="affectationagent-list"),
	path('affectationagent/ajout/', views.AffectationAgentCreateView.as_view(), name="nouvelle-affectationagent"),
	# OCCUPATION CRUD
	path('occupations/', views.OccupationListView.as_view(), name="occ-list"),
	path('occupation/ajout/', views.OccupationCreateView.as_view(), name="nouvelle-occupation"),
	# ORGANISATION CRUD
	path('organisation/ajout/', views.OrgaCreateView.as_view(), name="nouvelle-organisation"),
	path('organisation/<slug:slug>/modifications/', views.OrgaUpdateView.as_view(), name="org-modif"),
	path('organisation/<slug:slug>/suppression/', views.OrgaDeleteView.as_view(), name="org-delete"),
	path('organisation/<slug:slug>/', views.OrgaDetailView.as_view(), name="org-details"),
	path('organisations/', views.OrgaListView.as_view(), name="org-list"),
	# DOCUMENT CRUD
	path('document/ajout/', views.DocCreateView.as_view(), name="nouveau-doc"),
	path('documents/', views.DocListView.as_view(), name="doc-list"),
	# COMPTEURS OFFICIELS CRUD
	path('compteur_officiel/ajout/', views.CompteurOfficielCreateView.as_view(), name="nouveau-co"),
	path('compteur_officiel/<slug:slug>/modifications/', views.CompteurOfficielUpdateView.as_view(), name="co-modif"),
	path('compteur_officiel/<slug:slug>/suppression/', views.CompteurOfficielDeleteView.as_view(), name="co-delete"),
	path('compteur_officiel/<slug:slug>/', views.CompteurOfficielDetailView.as_view(), name="co-details"),
	path('compteurs_officiels/', views.CompteurOfficielListView.as_view(), name="co-list"),
	# RELEVE CRUD
	path('releve/ajout/', views.RlvCreateView.as_view(), name="nouveau-rlv"),
	path('releve/<int:pk>/modifications/', views.RlvUpdateView.as_view(), name="rlv-modif"),
	path('releve/<int:pk>/suppression/', views.RlvDeleteView.as_view(), name="rlv-delete"),
	path('releve/<int:pk>/', views.RlvDetailView.as_view(), name="rlv-details"),
	path('releves/', views.RlvListView.as_view(), name="rlv-list"),
]

src/page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
	path('', views.index, name='accueil'),
]

src/inventaire/forms.py
from django import forms
from .models import DocumentSite

class DocSiteForm(forms.ModelForm):
    class Meta:
        model = DocumentSite
        fields = ['doc', 'site',]

src/inventaire/views.py
from .models import *
from inventaire.resources import SiteResource
from .forms import DocSiteForm
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.forms.widgets import CheckboxSelectMultiple
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, UpdateView, DetailView, ListView, DeleteView, View, TemplateView
from django.db.models import When, Sum, Min, Count, Avg, Max, F, Q, ExpressionWrapper, DurationField, DateField, CharField, Case, Value
import random
from bootstrap_datepicker_plus import DateTimePickerInput

@login_required
def index(request):
	sites = Site.objects.all()
	total_site = sites.count()
	parcelles = Parcelle.objects.all()
	total_parcelle = parcelles.count()
	total_patris = parcelles.aggregate(Sum('patris'))['patris__sum']
	batiments = Batiment.objects.all()
	total_batiment = batiments.count()
	compt_off = CompteurOfficiel.objects.all()
	agents = Agent.objects.all()
	context = {
		'total_site':total_site,
		'sites':sites,
		'parcelles':parcelles,
		'total_parcelle':total_parcelle,
		'total_batiment':total_batiment,
		'total_patris':total_patris,
		'compt_off':compt_off,
		'agents':agents,
		}
	return render(request, 'inventaire/accueil.html', context)

@login_required
def annuaire(request):
	agents = list(Agent.objects.all())
	orgs = list(Organisation.objects.all())
#	agents_sample = random.sample(agents, 5)
#	orgs_sample = random.sample(orgs, 1)
	context = {
		'agents':agents,
		'orgs': orgs
		}
	return render(request, 'inventaire/annuaire.html', context)

class ComposantView(TemplateView):
	template_name = "inventaire/composants.html"

	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		context['compteurs_officiels'] = CompteurOfficiel.objects.all()
		return context
########################################################## RECHERCHE MULTIFIELD
from django.db.models import Q
from django.apps import apps

class SearchView(LoginRequiredMixin, ListView):
	template_name = "inventaire/search.html"

	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		rq = self.request.GET.get('q')
		context['terme_recherche'] = rq
		return context 

	def get_queryset(self,*args,**kwargs):
		excluded = ["Profile","TaggedItem","Tag",]
		modeles = [x for x in apps.get_models() if x.__name__ not in excluded]
		resultats = []
		rq = self.request.GET.get('q')
		for modele in modeles:
			fields = [x for x in modele._meta.fields if isinstance(x, CharField)]
			search_queries = [Q(**{x.name + "__icontains" : rq}) for x in fields]
			q_object = Q()
			for query in search_queries:
				q_object = q_object | query
			results = modele.objects.filter(q_object).distinct()
			if results:
				resultats.append({'nom':modele.__name__, 'resultats':results})
		return resultats
##################################################################### PRINT SITE
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas

class RapportPDFView(View):

	def get(self,request,*args,**kwargs):
		# Create a file-like buffer to receive PDF data.
		buffer = io.BytesIO()
		# Create the PDF object, using the buffer as its "file."
		p = canvas.Canvas(buffer)
		site = request.headers["Referer"].split('/')[-2]
		qs = Site.objects.filter(slug=site)
		p.drawString(10, 10, f"{ qs }")
		# Close the PDF object cleanly, and we're done.
		p.showPage()
		p.save()
		# FileResponse sets the Content-Disposition header so that browsers
		# present the option to save the file.
		buffer.seek(0)
		return FileResponse(buffer, as_attachment=True, filename='hello.pdf')
######################################################################### EXPORT
def export_sites(request):
	if request.method == 'POST':
		file_format = request.POST['file-format']
		dir_op = request.POST['dir-op']
		reg = request.POST['regio']
		if reg == "Bruxelles":
			regio = "BE-BRU"
		elif reg == "Wallonie":
			regio = "BE-WAL"
		elif reg == "Flandre":
			regio = "BE-VLG"
		else:
			regio = None
		qs = Site.objects.filter(service=dir_op).filter(region=regio)
		sites = SiteResource()
		dataset = sites.export(qs)
		if file_format == 'CSV':
			response = HttpResponse(dataset.csv, content_type='text/csv')
			response['Content-Disposition'] = 'attachment; filename="exported_sites.csv"'
			return response
		elif file_format == 'JSON':
			response = HttpResponse(dataset.json, content_type='application/json')
			response['Content-Disposition'] = 'attachment; filename="exported_sites.json"'
			return response
		elif file_format == 'XLS':
			response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
			response['Content-Disposition'] = 'attachment; filename="exported_sites.xls"'
			return response

	return render(request, 'inventaire/rapports/export.html')
###################################################################### SITE CRUD
class SiteListView(LoginRequiredMixin, ListView):
	model = Site
	paginate_by = 10
	template_name="inventaire/crud/site/site_list.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		directions = ['dicha','disippj','diaajmj']
		for direction in directions:
			context[direction] = Site.objects.filter(service=direction)
		context['total'] = Site.objects.all().count()
		return context

class SiteDetailView(LoginRequiredMixin, DetailView):
	model = Site
	template_name="inventaire/crud/site/site_details.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["related_tags"] = self.object.tags.similar_objects()
		documents = DocumentSite.objects.filter(site_id=self.object)
		parcelles = Parcelle.objects.filter(site_id=self.object)
		energies = CompteurOfficiel.objects.filter(livraison_id=self.object)
		consos = Releve.objects.filter(compteur__in=energies)
		context["images"] = documents.filter(doc__contains='/images/')
		context["documents"] = documents.exclude(doc__contains='/images/')
		context['agents'] = AffectationAgent.objects.filter(site_id=self.object)
		context['occupants'] = Occupation.objects.filter(site=self.object)
		context['surface_cadastrale_totale'] = parcelles.aggregate(Sum('patris'))['patris__sum']
		context['energies'] = energies
		context['consos'] = consos.values('compteur__identifiant', 'compteur__fluide', 'debut_periode__year', 'compteur__slug')\
							.order_by('compteur__identifiant', 'compteur__fluide')\
							.annotate(c_annuel=Sum('quantite'))
		return context

class SiteCreateView(LoginRequiredMixin, CreateView, SuccessMessageMixin):
	model = Site
	fields = ['nom','voirie','numero','boite','cp',
	'localite','region','tags', 'composition','service','edific']
	template_name="inventaire/crud/site/site_ajout.html"
	success_message = "Site ajouté à l'inventaire. Merci !"
	success_url = "/inventaire/site/{slug}/"

class SiteUpdateView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
	model = Site
	fields = ['nom','voirie','numero','boite','cp',
	'localite','region','tags', 'composition','service','edific']
	template_name="inventaire/crud/site/site_ajout.html"
	success_message = "%(nom)s a bien été modifié."

class SiteDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
	model = Site
	template_name="inventaire/crud/objet_a_effacer.html"
	success_url = reverse_lazy('inventaire:site-list')
################################################################## Parcelle CRUD
class ParcelleListView(LoginRequiredMixin, ListView):
	model = Parcelle
	paginate_by = 10
	template_name = "inventaire/crud/parcelle/parcelle_list.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['total'] = Parcelle.objects.all().count()
		return context

class ParcelleCreateView(LoginRequiredMixin, CreateView, SuccessMessageMixin):
	model = Parcelle
	fields = '__all__'
	template_name = "inventaire/crud/parcelle/parcelle_ajout.html"
	success_url = reverse_lazy('inventaire:parcelle-list')

	def get(self,request,*args,**kwargs):
		slug_site = self.request.headers["Referer"].split('/')[-2]
		form = super().get_form()
		if slug_site not in ["parcelles","inventaire"]:
				initial_d = self.get_initial()
				initial_d['site'] = Site.objects.get(slug=slug_site)
				form.initial = initial_d
		return render(request, self.template_name,{'form':form})

	def post(self,request,*args,**kwargs):
		form = self.get_form()
		if form.is_valid():
			super().form_valid(form)
			return HttpResponseRedirect(self.get_success_url())
		self.object = None
		return self.form_invalid(form)

class ParcelleDetailView(LoginRequiredMixin, DetailView):
	model = Parcelle
	fields = '__all__'
	template_name = "inventaire/crud/parcelle/parcelle_details.html"

class ParcelleUpdateView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
	model = Parcelle
	fields = '__all__'
	template_name = "inventaire/crud/parcelle/parcelle_ajout.html"
	success_message = "La fiche a bien été modifiée."
	success_url = reverse_lazy('inventaire:parcelle-list')

class ParcelleDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
	model = Parcelle
	template_name="inventaire/crud/objet_a_effacer.html"
	success_url = reverse_lazy('inventaire:parcelle-list')

################################################################## Batiment CRUD
class BatimentListView(LoginRequiredMixin, ListView):
	model = Batiment
	paginate_by = 10
	template_name = "inventaire/crud/batiment/batiment_list.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['total'] = Batiment.objects.all().count()
		return context

class BatimentCreateView(LoginRequiredMixin, CreateView, SuccessMessageMixin):
	model = Batiment
	fields = '__all__'

src/inventaire/templates/inventaire/crud/parcelle/parcelle_ajout.html
{% extends 'base_dash_adding.html' %}

{% block header_ajout_titre %}
{% if '/modifications/' in request.path %}
	Mise à jour
{% else %}
	Ajout
{% endif %} d'un terrain
{% endblock %}

{% block url-btn-retour %}{% url 'inventaire:parcelle-list' %}{% endblock %}

{% block form_itself %}
{% load crispy_forms_tags %}
<div class="card-body">
	<div class="card-text">
		<div class="row">
			<div class="col-lg-6 col-md-12">
			{{ form.site|as_crispy_field }}
			</div>
			<div class="col-lg-6 col-md-12">
			{{ form.droit|as_crispy_field }}
			</div>
		</div>
		<p>
			<em>
			<a href="{% url 'inventaire:nouveau-site' %}">
			Si un site n'est pas répertorié, vous pouvez le créer en cliquant ici.
			</a>
			</em>
		</p>
		<div class="row">
			<div class="col-lg-4 col-md-12">
			{{ form.nature|as_crispy_field }}
			</div>
			<div class="col-lg-4 col-md-12">
			{{ form.capakey|as_crispy_field }}
			</div>
			<div class="col-lg-4 col-md-12">
			{{ form.patris|as_crispy_field }}
			</div>
		</div>
	</div>
</div>
{% endblock %}

src/inventaire/templates/inventaire/crud/parcelle/parcelle_details.html
{% extends 'base_dash.html' %}
{% load static %}
{% load humanize %}

{% block titre_page %}{{ object }}{% endblock %}

{% block entete %}
<header class="page-header page-header-compact page-header-light border-bottom bg-gradient-primary-to-secondary mb-4">
    <div class="container-fluid">
        <div class="page-header-content">
            <div class="row align-items-center justify-content-between pt-3">
                <div class="col-auto mb-3">
                    <h1 class="page-header-title text-white">
                        <div class="page-header-icon text-white"><i class="fas fa-info"></i></div>
                        {{ object }}
                    </h1>
                </div>
                <div class="col-12 col-xl-auto mb-3">
                	<a class="btn btn-sm btn-light text-primary" href="{% url 'inventaire:parcelle-modif' slug=object.slug %}">Modifier</a>
                    <a class="btn btn-sm btn-light text-primary" href="{% url 'inventaire:parcelle-list' %}">Retour à la liste</a>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contenu %}
<div class="container">
    <div class="card">
        <div class="card-header">Matrice cadastrale</div>
        <div class="card-body">
          <dl class="row">
            <dt class="col-sm-6 text-right text-red">Division cadastrale:</dt>
            <dd class="col-sm-6 text-left">
              {{ object.division }}
            </dd>
            <dt class="col-sm-6 text-right text-red">Section:</dt>
            <dd class="col-sm-6 text-left">
              {{ object.section }}
            </dd>
            <dt class="col-sm-6 text-right text-red">Radical:</dt>
            <dd class="col-sm-6 text-left">
              {{ object.radical }}
            </dd>
            <dt class="col-sm-6 text-right text-red">Bis:</dt>
            <dd class="col-sm-6 text-left">
              {{ object.bis }}
            </dd>
            <dt class="col-sm-6 text-right text-red">Exposant:</dt>
            <dd class="col-sm-6 text-left">
              {{ object.exposant }}
            </dd>
            <dt class="col-sm-6 text-right text-red">Puissance:</dt>
            <dd class="col-sm-6 text-left">
              {{ object.puissance }}
            </dd>
          </dl>
          <hr>
          <dl class="row">
            <dt class="col-sm-6 text-right text-red">Contenance Patris (m²):</dt>
            <dd class="col-sm-6 text-left">
              {{ object.patris }}
            </dd>
            <dt class="col-sm-6 text-right text-red">Nature cadastrale:</dt>
            <dd class="col-sm-6 text-left">
              {{ object.nature }}
            </dd>
            <dt class="col-sm-6 text-right text-red">Situation patrimoniale:</dt>
            <dd class="col-sm-6 text-left">
              {{ object.get_droit_display }}
            </dd>
          </dl>
          <hr>
          <dl class="row">
            <dt class="col-sm-6 text-right text-red">Nombre de bâtiments</dt>
            <dd class="col-sm-6 text-left">{{ object.constructions.all|length }}</dd>
          </dl>        	
        </div>
    </div>
</div>
{% endblock %}

src/inventaire/templates/inventaire/crud/parcelle/parcelle_list.html
{% extends 'base_dash_listing.html' %}
{% load humanize %}

{% block titre_page %}Liste des terrains{% endblock %}

{% block header_list_titre %}{{ total }} terrains répertoriés{% endblock %}

{% block url-btn-ajouter %}{% url 'inventaire:nouvelle-parcelle' %}{% endblock %}

{% block entete_tbl %}
<thead>
	<tr>
		<th data-field="site" data-sortable="true">Site</th>
		<th data-field="capakey" data-sortable="true">CaPaKey</th>
		<th data-field="nature" data-sortable="true">Nature</th>
		<th data-field="droit" data-sortable="true">Droit</th>
		<th data-field="patris" data-sortable="true">Patris (m²)</th>
	</tr>
</thead>
{% endblock %}

{% block corps_tbl %}
<tbody>
	{% for p in object_list %}
	<tr>
		<td><a href="{{ p.site.get_absolute_url }}">{{ p.site }}</a></td>
		<td><a href="{{ p.get_absolute_url }}" type="button">{{ p.capakey }}</a></td>
		<td>{{ p.nature }}</td>
		<td>{{ p.get_droit_display }}</td>
		<td >{{ p.patris|floatformat:"0" }}</td>
	</tr>
	{% endfor %}
</tbody>
{% endblock %} 