src/aecds/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from utilisateur import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('page.urls')),
    path("glossaire/", include('glossaire.urls')),
    path('journal/', include('journal.urls')),
    path('inventaire/', include('inventaire.urls')),
]

url_users = [
    path('login/', user_views.LoginView.as_view(template_name="utilisateur/login.html"), name="login"),
    path('logout/', user_views.LogoutView.as_view(template_name="utilisateur/logout.html"), name="logout"),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name="utilisateur/password_reset.html"
            ),
        name="password_reset"),
    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name="utilisateur/password_reset_done.html"
            ),
        name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name="utilisateur/password_reset_confirm.html"
            ),
        name="password_reset_confirm"),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name="utilisateur/password_reset_complete.html"
            ),
        name="password_reset_complete"),
    path('profile/', user_views.profile, name="profile"),
    path('register/', user_views.register, name="register"),
]

urlpatterns += url_users

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/inventaire/urls.py
from django.urls import path
from . import views

app_name = 'inventaire'

urlpatterns = [
	path('', views.index, name='index'),
	path('annuaire/', views.annuaire, name='annuaire'),
	# RECHERCHE
	path('search/', views.SearchView.as_view(), name="recherche"),
	# ELEMENTS
	path('composants/', views.ComposantView.as_view(), name="composants"),
	# EXPORTATIONS
	path('sites/export/', views.export_sites, name="export-sites"),
	# SITE CRUD
	path('site/<slug:slug>/impression/', views.RapportPDFView.as_view(), name="site-print"),
	path('site/ajout/', views.SiteCreateView.as_view(), name="nouveau-site"),
	path('site/<slug:slug>/', views.SiteDetailView.as_view(), name="site-details"),
	path('sites/', views.SiteListView.as_view(), name="site-list"),
    path('site/<slug:slug>/modifications/', views.SiteUpdateView.as_view(), name="site-modif"),
    path('site/<slug:slug>/suppression/', views.SiteDeleteView.as_view(), name="site-delete"),
	# PARCELLE CRUD
	path('parcelle/ajout/', views.ParcelleCreateView.as_view(), name="nouvelle-parcelle"),
	path('parcelle/<slug:slug>/modifications/', views.ParcelleUpdateView.as_view(), name="parcelle-modif"),
	path('parcelle/<slug:slug>/suppressions/', views.ParcelleDeleteView.as_view(), name="parcelle-delete"),
	path('parcelles/', views.ParcelleListView.as_view(), name="parcelle-list"),
	path('parcelle/<slug:slug>/', views.ParcelleDetailView.as_view(), name="parcelle-details"),
	# BATIMENT CRUD
	path('batiments/', views.BatimentListView.as_view(), name="batiment-list"),
	path("batiment/ajout/", views.BatimentCreateView.as_view(), name="nouveau-batiment"),
	path("batiment/<slug:slug>/", views.BatimentDetailView.as_view(), name="batiment-details"),
	path("batiment/<slug:slug>/modifications/", views.BatimentUpdateView.as_view(), name="batiment-modif"),
	path("batiment/<slug:slug>/suppression/", views.BatimentDeleteView.as_view(), name="batiment-delete"),
	# NIVEAU CRUD
	path('niveaux/',views.NiveauListView.as_view(), name="niveaux-list"),
	path('niveau/ajout/', views.NiveauCreateView.as_view(), name="nouveau-niveau"),
	path('niveau/<int:pk>/',views.NiveauDetailView.as_view(), name="niveau-details"),
	path('niveau/<int:pk>/modifications/', views.NiveauUpdateView.as_view(), name="niveau-modif"),
	# MESURES SURFACE CRUD
	path('mesuredesurface/ajout/', views.MesureSurfaceCreateView.as_view(), name="nouvelle-mesuredesurface"),
	path("typedemesuredesurface/ajout/", views.TypeMesureSurfaceCreateView.as_view(), name="nouveau-typedemesuredesurface"),
	# MEMO CRUD
	path("memos/", views.MemoListView.as_view(), name="memo-list"),
	path("memo/ajout/", views.MemoCreateView.as_view(), name="nouveau-memo"),
	path("memo/<slug:slug>/", views.MemoDetailView.as_view(), name="memo-details"),
	path('memo/<slug:slug>/suppression/', views.MemoDeleteView.as_view(), name="memo-delete"),
	# RAPPORT
	path("rapports/", views.RapportListView.as_view(), name="rapport-list"),
	path('rapport/ajout/', views.RapportCreateView.as_view(), name="nouveau-rapport"),
	path('rapport/<int:pk>/modifications/', views.RapportUpdateView.as_view(), name="rapport-modif"),
	path("rapport/<int:pk>/suppression/", views.RapportDeleteView.as_view(), name="rapport-delete"),
	path("rapport/<int:pk>/", views.RapportDetailView.as_view(), name="rapport-details"),
	# AGENT CRUD
	path('agent/ajout/', views.AgentCreateView.as_view(), name="nouvel-agent"),
	path("agents/", views.AgentListView.as_view(), name="agent-list"),
	path('agent/<slug:slug>/', views.AgentDetailView.as_view(), name="agent-details"),
	path('agent/<slug:slug>/modifications/', views.AgentUpdateView.as_view(), name="agent-modif"),
	path("agent/<slug:slug>/suppression/", views.AgentDeleteView.as_view(), name="agent-delete"),
	# AGENTS DE SITE CRUD
	path('affectationagent/', views.AffectationAgentListView.as_view(), name="affectationagent-list"),
	path('affectationagent/ajout/', views.AffectationAgentCreateView.as_view(), name="nouvelle-affectationagent"),
	# OCCUPATION CRUD
	path('occupations/', views.OccupationListView.as_view(), name="occ-list"),
	path('occupation/ajout/', views.OccupationCreateView.as_view(), name="nouvelle-occupation"),
	# ORGANISATION CRUD
	path('organisation/ajout/', views.OrgaCreateView.as_view(), name="nouvelle-organisation"),
	path('organisation/<slug:slug>/modifications/', views.OrgaUpdateView.as_view(), name="org-modif"),
	path('organisation/<slug:slug>/suppression/', views.OrgaDeleteView.as_view(), name="org-delete"),
	path('organisation/<slug:slug>/', views.OrgaDetailView.as_view(), name="org-details"),
	path('organisations/', views.OrgaListView.as_view(), name="org-list"),
	# DOCUMENT CRUD
	path('document/ajout/', views.DocCreateView.as_view(), name="nouveau-doc"),
	path('documents/', views.DocListView.as_view(), name="doc-list"),
	# COMPTEURS OFFICIELS CRUD
	path('compteur_officiel/ajout/', views.CompteurOfficielCreateView.as_view(), name="nouveau-co"),
	path('compteur_officiel/<slug:slug>/modifications/', views.CompteurOfficielUpdateView.as_view(), name="co-modif"),
	path('compteur_officiel/<slug:slug>/suppression/', views.CompteurOfficielDeleteView.as_view(), name="co-delete"),
	path('compteur_officiel/<slug:slug>/', views.CompteurOfficielDetailView.as_view(), name="co-details"),
	path('compteurs_officiels/', views.CompteurOfficielListView.as_view(), name="co-list"),
	# RELEVE CRUD
	path('releve/ajout/', views.RlvCreateView.as_view(), name="nouveau-rlv"),
	path('releve/<int:pk>/modifications/', views.RlvUpdateView.as_view(), name="rlv-modif"),
	path('releve/<int:pk>/suppression/', views.RlvDeleteView.as_view(), name="rlv-delete"),
	path('releve/<int:pk>/', views.RlvDetailView.as_view(), name="rlv-details"),
	path('releves/', views.RlvListView.as_view(), name="rlv-list"),
]

src/page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
	path('', views.index, name='accueil'),
]

src/inventaire/models.py
import requests
from pathlib import Path
import uuid
import os, environ
from django.db import models
from django.urls import reverse
from django.conf import settings
from geopy.geocoders import Here
from crum import get_current_user
from tinymce.models import HTMLField
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.core.exceptions import ValidationError
##################################
# FONCTIONS & VARIABLES DIVERSES #
##################################
def get_doc_filename(instance, filename):
	base_name = os.path.basename(filename)
	name, ext = os.path.splitext(base_name)
	extension = ext.split('.')[1]
	if extension in ['jpg','jpeg','png','svg','tiff','gif','psd','eps','ai','bmp']:
		dossier = 'images'
	elif extension == 'dwg':
		dossier = 'plan_autocad'
	else:
		dossier = extension
	return "docs/"+str(instance.site.pk)+"/"+dossier+'/'+filename

BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(env_file=str(BASE_DIR / ".env"))
######################
# CLASSES ABSTRAITES #
######################
class Cachet(models.Model):
	'''Tous les objets héritent de cette classe pour que, lorsqu'un objet est
	manipulé, il reçoit un 'stamp' indiquant par qui et quand l'objet a été
	créé/modifié.
	Utilise la fonction get_current_user du package django-crum.
	IFC4 : Resource definition data schemas >> IfcUtilityResource >> IfcOwnerHistory
	'''
	created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	created_by = models.ForeignKey('auth.User', blank=True, null=True, editable=False,
	on_delete=models.CASCADE, default=None, related_name='%(app_label)s_%(class)s_created')
	modified = models.DateTimeField(auto_now=True, null=True, blank=True)
	modified_by = models.ForeignKey('auth.User', blank=True, null=True, editable=False,
	on_delete=models.CASCADE, default=None, related_name='%(app_label)s_%(class)s_modified')

	def save(self, *args, **kwargs):
		user = get_current_user()
		if user and not user.pk:
			user = None
		if not self.pk:
			self.created_by = user
		self.modified_by = user
		return super(Cachet, self).save(*args, **kwargs)

	class Meta:
		abstract = True

class CompositionElement(models.Model):
	"""Cette classe reprend les différentes compositions possibles des éléments
	de la structure spatiale. Et donc les classes Sites, Bâtiments, Niveaux et
	Locaux en héritent.
	Un élément peut être :
	- COMPLEXE : l'élément fait partie d'un groupe ou d'une aggrégation d'
	éléments similaires
	- ELEMENT : l'élément en tant que tel, non divisé
	- PARTIAL : partie ou sous élément
	IFC4 : Core data schemas >> IfcProductExtension >> IfcElementCompositionEnum
	"""
	COMPOSITION = (
		('C', 'COMPLEXE'),
		('E', 'ELEMENTAIRE'),
		('P', 'PARTIEL')
	)
	composition = models.CharField(max_length=1, choices=COMPOSITION,
	verbose_name="Composition", help_text="Déomposition de l'élément de structure spatiale")

	class Meta:
		abstract = True

class ServiceGestionnaire(models.Model):
	"""Organigramme de la DGI."""
	SERVICES = [
		("Service général des Infrastructures scolaires", (
				('DRBXL', 'Direction Régionale de Bruxelles'),
				('DRBW', 'Direction Régionale du Brabant Wallon'),
				('DRNO', 'Direction Régionale du Hainaut'),
				('DRLG', 'Direction Régionale de Liège'),
				('DRLX', 'Direction Régionale du Luxembourg'),
				('DRNM', 'Direction Régionale de Namur'),
			)
		),
		('Service général du Patrimoine et de la Gestion immobilière', (
				('DICHA', 'Direction des Implantations culturelles et des Hôpitaux académique'),
				('DISIPPJ', 'Direction des Implantations Sportives et des IPPJ'),
				('DIAAJMJ', "Direction des Implantations administratives, de l'Aide à la Jeunesse et des Maisons de Justice"),
			)
		),
		("Service général des Infrastructures scolaires subventionnées", (
				('SubLiege','Service de Liège'),
				('SubNam', 'Service de Namur'),
				('SubNO', 'Service du Hainaut'),
				('SubBrab', 'Service de Bruxelles et du Brabant Wallon'),
				('SubLux', 'Service du Luxembourg'),
			)
		)
	]

	service = models.CharField(max_length=10, choices=SERVICES,
	verbose_name="Service Gestionnaire", help_text="Le service au sein de la DGI.")

	class Meta:
		abstract = True

class AdressePostale(models.Model):
	# Champs à compléter par l'utilisateur (tous requis, sauf numero)
	voirie = models.CharField(max_length=255, verbose_name="Voirie", blank=True, null=True,
	help_text="En toutes lettres. Les noms de rue ne doivent inclure AUCUNE autre note ou information, telle que les noms de la sous-commune, etc.")
	numero = models.CharField(max_length=21, verbose_name="Numéro",
	help_text="Si 2 séries de chiffres distincts, utiliser tiret (« - »)", blank=True, null=True)
	boite = models.CharField(max_length=7, blank=True, null=True, verbose_name="boîte")
	localite = models.CharField(max_length=124, verbose_name="Localité",
	help_text="La localité, et non pas la commune.", blank=True, null=True)
	cp = models.CharField(max_length=6, verbose_name="Code postal",
	help_text="4 chiffres, pas d’initiale de pays,ni de code ISO", blank=True, null=True)
	REGION = (
		('BE-VLG','Flandre'),
		('BE-BRU','Bruxelles'),
		('BE-WAL','Wallonie')
	)
	region = models.CharField(max_length=6, choices=REGION, verbose_name="Région", blank=True, null=True)
	# Coordonnées WSG84
	latitude = models.FloatField(editable=False, default=0)
	longitude = models.FloatField(editable=False, default=0)
	# Champs complétés automatiquement (editable=False)
	commune = models.CharField(max_length=100, editable=False, blank=True, null=True)
	infomsg = models.CharField(max_length=275, editable=False, blank=True, null=True)
	is_best = models.BooleanField(editable=False, default=False)
	# Coordonnées Belge 1972 / Belgian Lambert 72
	X = models.FloatField(editable=False, default=0)
	Y = models.FloatField(editable=False, default=0)

	def coordonnees_adresse(self):
		''' Définition des latitude et longitude de l'Adresse.'''
		geoloc = Here(apikey=env('HERE_APIKEY'))
		try:
			loc = geoloc.geocode(self.voirie+', '+self.numero+', '+\
		self.localite).raw['Location']['NavigationPosition'][0]
			return (loc['Latitude'], loc['Longitude'])
		except:
			return (0,0)

	def check_if_is_best(self):
		url = "http://geoservices.wallonie.be/geolocalisation/rest/getPositionBySmartGeocoding/"
		adresse = str(self.cp)+'/'+self.localite+'/'+self.voirie+'/'+str(self.numero)
		try:
			r = requests.get(url+adresse).json()
			self.infomsg = r['infoMsg']
			if not r['infoMsg'] and not r['errorMsg'] and r['errorCode'] == 0:
				self.is_best = True
			else:
				self.is_best = False
			return r['x'], r['y'], r['rue']['commune']
		except requests.exceptions.RequestException as e:
			self.infomsg = str(e)
			return (0,0,"")

	def __str__(self):
		return self.voirie+', '+str(self.numero)+' - '+str(self.cp)+' '+self.localite

	def save(self, *args,**kwargs):
		self.slug = slugify(self)
		if self.region != "BE-VLG":
			try:
				self.X, self.Y, self.commune = self.check_if_is_best()
			except:
				self.X, self.Y, self.commune = (0,0,"")
		self.latitude, self.longitude = self.coordonnees_adresse()
		return super().save(*args,**kwargs)

	class Meta:
		abstract = True

class AdresseTelecom(models.Model):
	'''Coordonnées de contact d'une personne et/ou d'une organisation.
	Au moins une coordonnée doit être remplie.
	Procédure de validation à écrire.
	IFC4 : Resource definition data schemas >> IfcActorResource >> IfcTelecomAddress
	'''
	phone = models.CharField(max_length=15, blank=True, null=True)
	gsm = models.CharField(max_length=15, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	homepage = models.URLField(blank=True, null=True)

	def clean(self):
		if not (self.phone or self.gsm or self.email or self.homepage):
			raise ValidationError("Au moins une coordonnée doit être indiquée.")

	class Meta:
		abstract = True

class Personne(models.Model):
	'''Cette classe représente un être humain.
	IFC4 : Resource definition data schemas >> IfcActorResource >> IfcPerson
	'''
	GENRE = (
	('M','Monsieur'),
	('F','Madame'),
	('X','Non précisé')
	)
	genre = models.CharField(max_length=1, choices=GENRE)
	nom = models.CharField(max_length=225)
	prenom = models.CharField(max_length=124)

	def __str__(self):
		return self.prenom+' '+self.nom

	class Meta:
		abstract = True
		ordering = ('nom',)
#####################
# CLASSES PARTAGEES #
#####################
class Organisation(Cachet, AdresseTelecom):
	nom = models.CharField(max_length=255, help_text="Nom complet de l'Organisation")
	slug = models.SlugField(max_length=255, unique=True, editable=False)
	bce_ne = models.CharField(max_length=10, help_text="Dix chiffres, sans les points",
	blank=True, verbose_name="Numéro BCE")
	fase = models.PositiveIntegerField(help_text="n°FASE, si établissement scolaire", blank=True, null=True)

	def __str__(self):
	   return self.nom.upper()

	def save(self,*args,**kwargs):
		self.slug = slugify(self)
		return super().save(*args,**kwargs)

	def get_absolute_url(self):
		return reverse('inventaire:org-details', args=[self.slug])

class Occupation(Cachet):
	nom = models.CharField(max_length=255, null=True, blank=True, verbose_name="Nom donné à l' occupation")
	orga = models.ForeignKey('Organisation', on_delete=models.CASCADE,
	related_name="occupants", verbose_name="Occupant", null=True)
	site = models.ForeignKey('Site', on_delete=models.CASCADE, related_name="occupations",
	verbose_name="Site d'implantation")
	bce_ue = models.CharField(max_length=10, help_text="Dix chiffres, sans les points",
	blank=True, verbose_name="Numéro d'établissement BCE")

	def __str__(self):
		if not self.nom:
			return str(self.site)
		else:
			return self.nom

	def get_absolute_url(self):
		return reverse('org-list')

class Agent(Personne, AdresseTelecom):
	'''Un agent est une personne qui travaille au sein de la Direction Générale
	des Infrastructures du Secrétariat Général du Ministère de la Fédération
	Wallonie Bruxelles.
	IFC4 : NONE'''

src/inventaire/forms.py
from django import forms
from .models import DocumentSite

class DocSiteForm(forms.ModelForm):
    class Meta:
        model = DocumentSite
        fields = ['doc', 'site',]

src/inventaire/templates/inventaire/crud/batiment/batiment_ajout.html
{% extends 'base_dash_adding.html' %}

{% block header_ajout_titre %}
{% if '/modifications/' in request.path %}
	Mise à jour
{% else %}
	Ajout
{% endif %} d'un batiment
{% endblock %}

{% block url-btn-retour %}{% url 'inventaire:batiment-list' %}{% endblock %}

{% block form_itself %}
{% load crispy_forms_tags %}
<div class="card-body">
	<div class="card-text">
	  <div class="row">
	    <div class="col-lg-4 col-md-12">
	      {{ form.parcel|as_crispy_field }}
	    </div>
	    <div class="col-lg-4 col-md-12">
	      {{ form.id_regional|as_crispy_field }}
	    </div>
	    <div class="col-lg-4 col-md-12">
	      {{ form.composition|as_crispy_field }}
	    </div>
	  </div>
	  <p>
	    <em>
	      <a href="{% url 'inventaire:nouvelle-parcelle' %}">
	        Si un terrain n'est pas répertorié, vous pouvez le créer en cliquant ici.
	      </a>
	    </em>
	  </p>
	  <div class="row">
	    <div class="col-lg-6">
	      {{ form.nom|as_crispy_field }}
	    </div>
	    <div class="col-lg-6">
	      {{ form.desc|as_crispy_field }}
	    </div>
	  </div>
	  <div class="row">
	    <div class="col-lg-4 col-md-12">
	      {{ form.nbr_niveau|as_crispy_field }}
	    </div>
	    <div class="col-lg-4 col-md-12">
	      {{ form.annee_cstr|as_crispy_field }}
	    </div>
	    <div class="col-lg-4 col-md-12">
	      {{ form.shape_area|as_crispy_field }}
	    </div>
	  </div>
	</div>
</div>
{% endblock %}

src/inventaire/templates/inventaire/crud/batiment/batiment_details.html
{% extends 'base_dash.html' %}
{% load static %}
{% load humanize %}

{% block titre_page %}{{ object }}{% endblock %}

{% block entete %}
<header class="page-header page-header-compact page-header-light border-bottom bg-gradient-primary-to-secondary mb-4">
    <div class="container-fluid">
        <div class="page-header-content">
            <div class="row align-items-center justify-content-between pt-3">
                <div class="col-auto mb-3">
                    <h1 class="page-header-title text-white">
                        <div class="page-header-icon text-white"><i class="fas fa-info"></i></div>
                        {{ object }}
                    </h1>
                </div>
                <div class="col-12 col-xl-auto mb-3">
                	<a class="btn btn-sm btn-light text-primary" href="{% url 'inventaire:batiment-modif' slug=object.slug %}">Modifier</a>
                    <a class="btn btn-sm btn-light text-primary" href="{% url 'inventaire:batiment-list' %}">Retour à la liste</a>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contenu %}
<div class="container">
    <div class="card">
        <div class="card-header">{{ object }}</div>
        <div class="card-body">
          <dl class="row">
            <dt class="col-sm-3">Nom usuel</dt>
            <dd class="col-sm-9">{{ object.nom }}</dd>

            <dt class="col-sm-3">Site</dt>
            <dd class="col-sm-9"><a href="{% url 'inventaire:site-details' slug=object.parcel.site.slug %}">{{ object.parcel.site }}</a></dd>

            <dt class="col-sm-3">ID Regional</dt>
            <dd class="col-sm-9">{{ object.id_regional }}</dd>

            <dt class="col-sm-3">Description</dt>
            <dd class="col-sm-9">{{ object.desc }}</dd>

            <dt class="col-sm-3">Complexité du bâtiment</dt>
            <dd class="col-sm-9">{{ object.get_composition_display }}</dd>

            <dt class="col-sm-3">Parcelle cadastrale</dt>
            <dd class="col-sm-9">{{ object.parcel.capakey }}</dd>

            <dt class="col-sm-3">Année de construction</dt>
            <dd class="col-sm-9">{{ object.annee_cstr }}</dd>
          </dl>
            <hr>
          <div class="row">
            <div class="col">
          <ul class="list-unstyled">
            <li>Surface bâtie au sol: {{ object.shape_area|floatformat:"1" }} m²</li>
            {% if niveaux %}
            <li>Surface par niveaux:</li>
              <ul>
              {% for niv in niveaux %}
                <li>
                  Niveau {{ niv.nom }} :
                  {% for mes in niv.niveaux.all %}
                    {{ mes.valeur|floatformat:"0" }} m² [{{ mes.type }}]
                  {% endfor %}
                </li>
              {% endfor %}
                <li>Surface Totale : <strong>{{ somme_surface_niveaux|floatformat:"0" }} m²</strong></li>
              </ul>
            {% endif %}
            {% if mes_bat %}
            <li>Mesures du bâtiment:</li>
              <ul>
                {% for mes in mes_bat %}
                <li>
                  {{ mes.valeur|floatformat:"0" }} m² [{{ mes.type }}]
                </li>
                {% endfor %}
              </ul>
            {% endif %}
            <a class="float-right" href="{% url 'inventaire:nouvelle-mesuredesurface' %}">Ajouter une mesure de surface</a>
          </ul>              
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock %}

src/inventaire/templates/inventaire/crud/batiment/batiment_list.html
{% extends 'base_dash_listing.html' %}
{% load humanize %}

{% block titre_page %}Liste des bâtiments{% endblock %}

{% block header_list_titre %}{{ total }} bâtiments répertoriés{% endblock %}

{% block url-btn-ajouter %}{% url 'inventaire:nouveau-batiment' %}{% endblock %}

{% block entete_tbl %}
  <thead>
    <tr>
      <th data-field="site" data-sortable="true">Site</th>
      <th data-field="nom" data-sortable="true">Nom usuel</th>
      <th data-field="idr" data-sortable="true">ID regional</th>
    </tr>
  </thead>
{% endblock %}

{% block corps_tbl %}
  <tbody>

        {% for bat in object_list %}
          <tr>
            <td><a href="{% url 'inventaire:site-details' slug=bat.parcel.site.slug %}">{{ bat.parcel.site }}</a></td>
            <td>{% if bat.nom %}{{ bat.nom }}{% else %}<a href="{% url 'inventaire:batiment-modif' slug=bat.slug %}">Ajouter un nom usuel</a>{% endif %}</td>
            <td><a href="{% url 'inventaire:batiment-details' slug=bat.slug %}">{{ bat.id_regional }}</a></td>
          </tr>
        {% endfor %}

  </tbody>
{% endblock %} 